<?php
/*
 Template Name: Privacy Policy Bad
 */
get_header("badadjohnny");
?>


<div class="pu-bad-page">

    <!--Section2-->

    <section class="pu-bad-story-wrapper pu-bad-common-text"
	style="background: url(<?php echo wp_get_attachment_url(get_theme_mod('lwp-privacybd-callout-image')); ?>)">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Bad Ad Johnny PRIVACY POLICY:</h1>
                    <div class="pu-zro-lg-wrapper">
                        <img src="<?php echo wp_get_attachment_url( 156 ); ?>">
                        <p> We are in the industry of stopping ads, fighting malware and dodging trackers. </p>
                        <h3> Strict Zero Log Policy </h3>
                        <p> Bad Ad Johnny, or its parent brand PureVPN, ("The Company") does not store any data or maintain any logs. Furthermore The Company will not generate any monetary benefit by selling or trading the user's email address and,or any other personally identifiable information (PII).</p>
                        <h3> Acceptable Ads Are Not Acceptable Here </h3>
                        <p> It is needless to say that we take privacy extremely seriously. We do not have an “acceptable ads” policy. For us, the only acceptable ads are the ones you, as a user, deem acceptable; we do not and will not enforce any ads on you, with or without you knowing about it.</p>
                        <h3> Communications with Server </h3>
                        <p> The Bad Ad Johnny extension communicates with its servers and that communication is encrypted. This way, no third-party can ever know what your preferences are with regards to the usage of the extension or which ads you have allowed or specifically blocked. </p>
                        <h3> Access to Data </h3>
                        <p> You might get a message about the extension requiring access to your data. You can confidently assume that the message is auto generated by the browser. This is because the Bad Ad Johnny extension needs to read the data being displayed on a web page to stop ads, fight malware and dodge trackers. </p>
                        <p> We reserve the right to amend/update/revise this policy as and when needed. </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--Section2-->

</div>


<?php
get_footer("badadjohnny");
?>


